#!/bin/bash
# brew install pkg-config	
# export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.0.13/lib/pkgconfig/


rm ./resume.html
rm ./resume.pdf

# Create virtual environment
python ./create-venv-script.py
python ./venv-script.py ./venv

#  Build xcode project
cd ./AddressBook/
xcodebuild
cd ./..

# Activate created virtual environment
source ./venv/bin/activate

# Convert MD to HTML
echo "<head><meta charset=\"UTF-8\"/></head>" > resume.html
python -m markdown -x tables -x nl2br resume.md >> resume.html

# Substitute values from AddressBook
./AddressBook/build/Release/AddressBook ./resume.html

# Convert HTML to PDF
weasyprint ./resume.html resume.pdf -s ./print.css


# Cleanup
rm ./resume.html
rm ./venv-script.py

# Rename resume
mv ./resume.pdf "./Nikolay Pshenichny.pdf"